spring:
  application:
    name: auto-catalog

  datasource:
      driver-class-name: org.postgresql.Driver
      url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
      username: postgres
      password: 1111

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auto-catalog-test.eu.auth0.com/

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: auto_catalog
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    baseline-on-migrate: true

logging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.web: DEBUG


server:
  port: 8080


auth0:
  audience: https://my-api.example.com

springdoc:
    api-docs:
      path: /auto-catalog-docs
    swagger-ui:
          path: /swagger-ui-custom.html
          operationsSorter: method

#http://localhost:8080/swagger-ui/index:html#/:
#/auto-catalog-docs